apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker-deployment
  template:
    metadata:
      labels:
        component: worker-deployment
    spec:
      containers:
      - name: worker
        image: sorin1333/multi-worker
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'  
        resources:
          limits:
            memory: "32Mi"
            cpu: "5m"
